spring:
  application:
   name: product-service
   
  # db 설정   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.51:3306/dream?serverTimezone=UTC&characterEncoding=UTF-8
    username: dream
    password: 1234
  resources:
     static-locations: classpath:/resources/static/**
