#  설정은 git에 있음.(https://github.com/JongbaekKIm/Dream_MSA.git)

server:
  port: 8004

spring:
  application:
    name: loan-service  # git에 있는 확장자 제외한 설정파일 이름.
    
    # 사용하려면 gradle에 config, web, actuator 추가해야 함.
#  config:              # gradle에 config 추가.
#   import: optional:configserver:http://localhost:8888  # config 서버 위치   
  devtools:
     livereload:
       enabled: true
     restart:
      enabled: true
#---
## actuator를 이용하여 서버 재시작 없이 변경내용 반영 가능하게 함.
#management:
#  endpoints:
#   web:
#    exposure:
#     include: refresh 


#외부      
#kafka 설정
kafka:
  server_endpoint: 127.0.0.1:9092
  topic_name: my-topic
  group_id: consumer-loan-service
  
---
  # db 설정 
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.51:3306/dream?serverTimezone=UTC&characterEncoding=UTF-8
    username: dream
    password: 1234
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.54:8080/auth/realms/MSA/protocol/openid-connect/certs

---
# mybatis 연동 설정   
mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 유레카 클라이언트 설정            
eureka:
  instance:
    instance-id: loan-microservice-instance # eureka에 등록되는 id 값
  client:
    register-with-eureka: true  # 유레카에 등록할지 여부.
    fetch-registry: true  # 유레카에서 조회할지 여부
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:8761/eureka
      
keycloak:
  realm: MSA
  bearer-only: true
  ssl-required: external
  resource: spring-gateway-client
  auth-server-url: http://192.168.1.54:8080/auth
  credentials:
    secret: WEcACPUTWPfuhPrEz3bBaHcl7OLLmYX1
=======
      defaultZone: http://localhost:8761/eureka # 서비스를 등록할 서버 주소를 지정
      
>>>>>>> ec6a23e06640487a52c2dfa0c7a6dce6f633945e

